### ISSUE TITLE
feat: allow for alternative separator character in CSV files

### ISSUE THREAD

**Issue by bkuri** [samk-dev/nuxt-translation-manager#10]
Commas are far too common in text and replacing them with `&#44;` apparently doesn't actually render the commas on the final text. Please add a setting to allow for the separator character to be modified to something less common (ie pipe char).

Thanks!

**Comment by bkuri** [comment]
Please see PRs #11 and #12.

**Comment by samk-dev** [comment]
Hey @bkuri thanks for the suggestion and PR.

Adding the flexibility to set a custom separator is good, please take note that if you need to do pluralization with `vue-i18n` it uses the pipe char to do that, I have an example [here](https://github.com/samk-dev/nuxt-translation-manager-module-usage-example/blob/main/lang/translations.csv). You can use commas in your translations string by wrapping them in `double quotes`  

`using-comma,"Using comma, then some text","Using comma, then some text","Using comma, then some text"`

**Comment by bkuri** [comment]
@samk-dev thanks for the heads up regarding the pipe character. :+1: 

I could've sworn that I had tried using quotes to separate between translations. At any rate, not having to use them in the first place should be more maintainable in the long run.

I've now sent a proper PR your way. Sorry for the all the PR noise earlier. Cheers!

**Comment by samk-dev** [comment]
@bkuri thanks for the pr. I'll release it tonight or tomorrow.
