### ISSUE TITLE
Release new NPM version 

### ISSUE THREAD

**Issue by phillipmohr** [samk-dev/nuxt-translation-manager#23]
Hello, I need the separator option which was merged here: https://github.com/samk-dev/nuxt-translation-manager/pull/13 

However, it seems like this change is not yet been released for the NPM package.

**Comment by samk-dev** [comment]
hey Philip, this will be released maybe this week, I am finishing my last tests with making sure the module is `V4` compatible

**Comment by samk-dev** [comment]
@phillipmohr released
